#!/bin/bash
# Factorize as many numbers as possible into a product of two smaller numbers.
if [ $# -ne 1 ]; then
	echo "Usage: factors <file>" 
	exit 1
fi

if [ ! -f $1 ]; then
	echo "File not Fount"
	exit 2
fi

while read n; do
p=1
q=$n
	for ((i=2; i*i<=n; i++)); do
		if [ $((n % i)) -eq 0 ]; then
			p=$i
			q=$((n / i))
			break
		fi
	done
	echo "$n=$q*$p"
done < $1
	
